name: CI-CD Docker Azure Pipeline

on:
  push:
    branches:
      - main

jobs:

# ---------------- LINT ----------------
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Linting files..."

# ---------------- TEST ----------------
  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - run: test -f index.html
      - run: test -f style.css
      - run: test -f script.js

# ---------------- BUILD ----------------
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/ci-cd-demo:${{ github.sha }} .

# ---------------- PUSH ----------------
  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Push Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/ci-cd-demo:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/ci-cd-demo:${{ github.sha }}

# ---------------- DEPLOY ----------------
  deploy:
    runs-on: ubuntu-latest
    needs: push

    steps:
      - name: Azure Login
        run: |
          az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy message
        run: echo "Deploying container to Azure App Service (next step)"
