name: Flask CI-CD

on:

  push:

    branches:

      - dev


jobs:


# ---------------- LINT ----------------

  lint:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v4


      - uses: actions/setup-python@v5

        with:

          python-version: '3.12'


      - run: pip install flake8


      - run: flake8 .



# ---------------- TEST ----------------

  test:

    runs-on: ubuntu-latest

    needs: lint


    steps:

      - uses: actions/checkout@v4


      - uses: actions/setup-python@v5

        with:

          python-version: '3.12'


      - run: pip install -r requirements.txt


      - run: pytest



# ---------------- BUILD ----------------

  build:

    runs-on: ubuntu-latest

    needs: test


    steps:

      - uses: actions/checkout@v4


      - run: |

          docker build \

          -t ${{ secrets.ACR_LOGIN_SERVER }}/employee-app:${{ github.sha }} .



# ---------------- PUSH ----------------

  push:

    runs-on: ubuntu-latest

    needs: build


    steps:

      - uses: actions/checkout@v4


      - run: |

          echo ${{ secrets.ACR_PASSWORD }} |

          docker login ${{ secrets.ACR_LOGIN_SERVER }}

          -u ${{ secrets.ACR_USERNAME }}

          --password-stdin


      - run: |

          docker build \

          -t ${{ secrets.ACR_LOGIN_SERVER }}/employee-app:${{ github.sha }} .


          docker push \

          ${{ secrets.ACR_LOGIN_SERVER }}/employee-app:${{ github.sha }}



# ---------------- DEPLOY ----------------

  deploy:

    runs-on: ubuntu-latest

    needs: push


    steps:

      - run: |

          az login --service-principal \

          --username ${{ secrets.AZURE_CLIENT_ID }} \

          --password ${{ secrets.AZURE_CLIENT_SECRET }} \

          --tenant ${{ secrets.AZURE_TENANT_ID }}


      - run: |

          echo "Deploying employee application..."
